// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvIH5wwZQSwmU84bRfElufY0ygYCg87Lg',
    appId: '1:82823111595:web:01afdda638e1c6c6f268ee',
    messagingSenderId: '82823111595',
    projectId: 'vegaspectrum',
    authDomain: 'vegaspectrum.firebaseapp.com',
    storageBucket: 'vegaspectrum.firebasestorage.app',
    measurementId: 'G-QS0Z1E81FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjtgNTOh55qGMllB_mKdeO9zoM-UXKMaA',
    appId: '1:82823111595:android:1a79079d8fc18a7bf268ee',
    messagingSenderId: '82823111595',
    projectId: 'vegaspectrum',
    storageBucket: 'vegaspectrum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8tHVcRirSqMLgwsWsf8EvPTBoFQ13G0',
    appId: '1:82823111595:ios:9c26baf89e83f06bf268ee',
    messagingSenderId: '82823111595',
    projectId: 'vegaspectrum',
    storageBucket: 'vegaspectrum.firebasestorage.app',
    iosBundleId: 'com.example.vegaSpectrumV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY8tHVcRirSqMLgwsWsf8EvPTBoFQ13G0',
    appId: '1:82823111595:ios:9c26baf89e83f06bf268ee',
    messagingSenderId: '82823111595',
    projectId: 'vegaspectrum',
    storageBucket: 'vegaspectrum.firebasestorage.app',
    iosBundleId: 'com.example.vegaSpectrumV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvIH5wwZQSwmU84bRfElufY0ygYCg87Lg',
    appId: '1:82823111595:web:f92d15e13d6260faf268ee',
    messagingSenderId: '82823111595',
    projectId: 'vegaspectrum',
    authDomain: 'vegaspectrum.firebaseapp.com',
    storageBucket: 'vegaspectrum.firebasestorage.app',
    measurementId: 'G-YK3XR6BVB9',
  );
}
